### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by rmaupin** [lduchosal/ipnetwork#1]
The IPv6 support is wrong. IPv6 doesn't have the concept of broadcast, so there are no broadcast addresses.  Unlike IPv4, IPv6 uses the subnet (zero) address as the first usable address, and the last usable address is what you are calling the broadcast address.  The usable addresses for a standard **/64** subnet run from **subnet::** to **subnet::ffff:ffff:ffff:ffff**.

With a few exceptions, IPv6 subnets will be **/64**.  You can use **/128** for loopbacks and addresses, **/126** or **/127** for point to point links, **/96** for IPv4 mapped addresses (**;;ffff;a.b.c.d**), and link-local networks (**fe80::**) are /10.  All subnets for connecting devices (PCs, servers, etc.) should be **/64**, else you will break some IPv6 functionality.  The IPv6 address format is **network:subnet:interface**.

**Comment by lduchosal** [comment]
Thanks for pointing this out.
This has been resolved in v2.0.3

**Comment by rmaupin** [comment]
You are welcome.

 

You may want to peruse RFC 5952, A Recommendation for IPv6 Address Text Representation <https://tools.ietf.org/html/rfc5952>  for output formatting.  I wrote some IP code, and I put in a lot to make sure that it will accept IPv6 addresses in just about any legal format, but it returns any addresses in the canonical format prescribed in the RFC.

 

Also, you can probably skip the mask output for IPv6 addressing.  While masks will be used internally in your code, there is no real use for the mask outside the code since IPv6 use is only with the CIDR notation.

 

I have noticed that a lot of people who are familiar with IPv4 try to use the IPv4 mindset with IPv6, and that just doesn’t work.  In many cases, IPv6 is easier to work with than IPv4; it’s just that people see the large, complex-looking address and put up a mental wall.  With standard /64 subnets used almost everywhere, calculating subnets will just about be a thing of the past.  With over 18 quintillion addresses per /64 subnet, there is no worry about address exhaustion in a subnet, and, as easy as it is to get a /48 network (even for personal use), you can have 65,536 /64 subnets per network, so they aren’t in short supply either.

 

What can be confusing is that IPv6 will have multiple addresses per interface because that is not common in IPv4.  Every interface will have at least a link-local address in the same network (fe80::/10) so you have to worry about the zone or interface identifier on the end of link-local  addresses (e.g., the %15 on the end of the link-local address fe80::5cb0:ae4a:2582:23c4%15).  Interfaces mays also have one or more other addresses.

 

Global addresses are in the range of 2000::/3, so they either start with a “2” or a “3” in a full 16-bit word (four hex digits before the first colon).  This is not likely to change for the foreseeable future.  As it was explained to me, if we have 19 billion people on Earth in the year 2100, that range would allow for several thousand /48 networks, at 65,536 /64 subnets per network, for each person on earth, and it is still only and eighth of the full IPv6 address range. (at 19 billion people on earth, we probably won’t be worrying about networking since we will have other, overriding concerns).

 

IPv6 multicast addressing (ff00::/8) is a bit complicated with flags (4 bits) and scopes (4 bits) defined and reserved for the 8 bits following the “ff,” but it is easy to identify a multicast address at a glance since it always starts with “ff.”
