### ISSUE TITLE
CIDR list issue

### ISSUE THREAD

**Issue by alandoherty** [lduchosal/ipnetwork#110]
Hi,

I'm not entirely sure if I'm doing something wrong here, but I had an expectation that FilterEnum.Usable would not exclude addresses that are perfectly valid. For example this code:

```csharp
IPNetwork network = IPNetwork.Parse("51.195.164.144/28");
var addresses = network.ListIPAddress(FilterEnum.Usable);
```

Excludes both `51.195.164.144` and `51.195.164.159`. Is this a bug or intended behaviour?

**Comment by agowa338** [comment]
- 51.195.164.144 is your network address
- 51.195.164.159 is your broadcast address

=> Therefore both are not usable by definition.

**Comment by lduchosal** [comment]
This is intended behaviour.
