### ISSUE TITLE
The IPNetwork.subnet does not work

### ISSUE THREAD

**Issue by KvasirSG** [lduchosal/ipnetwork#12]

**Comment by r00t-s** [comment]
Can you please provide an example regarding what isn't functioning? The code below works for me:

            var ipnetwork = IPNetwork.Parse("192.168.0.0/24");
            const byte cidr = 32;

            var subnets = IPNetwork.Subnet(ipnetwork, cidr);
            var index = 0;
            foreach (var subnet in subnets)
            {
                Console.WriteLine($"IPNetwork.Subnet #{index}={subnet}");
                index++;
            }

**Comment by lduchosal** [comment]
Would you please provide a test that shows the failed behaviour in a new issue ?
Thanks
