### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by petroemil** [lduchosal/ipnetwork#13]
If it's possible, could you please migrate it over .NETCoreApp or more likely .NETStandard? Would be nice if this library would be useable from .NET Core applications.

**Comment by LordMike** [comment]
Chiming in here. Would be immensely helpful :)

**Comment by lduchosal** [comment]
Thanks for the idea. I'll dig into it.

**Comment by LordMike** [comment]
Just to add on this, VS2017 was recently released, which brought with it the new csproj format. Don't use project.json - it's dead.

**Comment by nathan-alden** [comment]
Chiming in for .NET Standard support. I'd hate to have to write my own library to do this when it seems like this library is perfect.

Side note: You should really avoid using the `System` namespace; it's generally reserved for Microsoft's own official libraries.

**Comment by masaeedu** [comment]
I've migrated the code to the new MSBuild SDK style projects in #16 and tests seem to be working. A nuget produced using `dotnet pack` works with .NET Core and full framework projects alike.
