### ISSUE TITLE
TryParse does not return `false` on all invalid IPv6 addresses

### ISSUE THREAD

**Issue by stujfiter** [lduchosal/ipnetwork#131]
I have run into an issue where TryParse() does not throw an exception when given an invalid IPv6 address.

Sample Code:
`IPNetwork network;
  IPNetwork.TryParse("g001:02b8::/64", out network)`

I have validated this bug against version 2.5.247

**Comment by GF-Huang** [comment]
Do you know the convention of Parse and TryParse in C#?

**Comment by stujfiter** [comment]
Poor name for the bug.  I will attempt to rename.

Consider this:
```
[Fact]
        public void IpNetworkTest()
        {
            Assert.False(IPNetwork.TryParse("g001:02b8::/64", out _));
        }
```

This test fails as TryParse fails to detect the invalid 'g' character

**Comment by lduchosal** [comment]
IPNetwork library sanitanize its input before trying to parse it as an IPNetwork. It removes invalid chars beforehand and returns the parsed IPNetwork. 

I would say, this is intended behaviour. We could add behaviour with additional method TryExactParse... or something. PR Welcome.

**Comment by stujfiter** [comment]
@lduchosal, can this be documented as the intended behavior or so others know that they will need to check for invalid characters before sending to TryParse?  I'm happy to make a PR to document it, but I did not see any documentation on TryParse so do not know where to put such documentation other than as comments in the code.

**Comment by RobThree** [comment]
_"IPNetwork library sanitanize its input before trying to parse it as an IPNetwork."_
Which is a design decision that you made and it's all up to you ofcourse. However:

```c#
var result = IPAddress.TryParse("g001:02b8::", out var ip);
```

This will return `false`; I would argue that for [the least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) the 'sanitization' shouldn't be done and `false` should simply be returned.

**Comment by lduchosal** [comment]
@RobThree thanks for your insight. I do agree with the least surprise principle. I will increment version number and add a note about this change of behaviour into the release note.
