### ISSUE TITLE
Supernet not working correctly

### ISSUE THREAD

**Issue by BigPacket** [lduchosal/ipnetwork#15]
Greetings,

Although the example "192.168.0.0/24 + 192.168.1.0/24 = 192.168.0.0/23" works find. I found that the below doesn't and give a /24 when it should be /22.

IPNetwork ipnetwork1 = IPNetwork.Parse("200.16.0.0/24");
IPNetwork ipnetwork2 = IPNetwork.Parse("200.16.3.0/24");
IPNetwork[] ipnetwork3 = IPNetwork.Supernet(new[] { ipnetwork1, ipnetwork2 });
MessageBox.Show(String.Format("{0} + {1} = {2}", ipnetwork1, ipnetwork2, ipnetwork3[0]));

Hope you're able to fix this.
Thanks.

**Comment by lduchosal** [comment]
Super try to create a **perfect matching** supernet.
In your case, we are missing the 200.16.1.0/24 and 200.16.2.0/24 subnet to have a perfect supernet.

Solution 1: add the missing subnets 

            IPNetwork ipnetwork1 = IPNetwork.Parse("200.16.0.0/24");
            IPNetwork ipnetwork2 = IPNetwork.Parse("200.16.1.0/24");
            IPNetwork ipnetwork3 = IPNetwork.Parse("200.16.2.0/24");
            IPNetwork ipnetwork4 = IPNetwork.Parse("200.16.3.0/24");

            IPNetwork result = IPNetwork.Supernet(new[] { ipnetwork1, ipnetwork2, ipnetwork3, ipnetwork4 })[0];
            IPNetwork expected = IPNetwork.Parse("200.16.0.0/22");

            Assert.AreEqual(expected, result, "supernet");

Solution 2: use WideSubnet

The wide subnet will find the smallest subnest that fits the given ips

            string start = "200.16.0.0";
            string end = "200.16.3.255";

            IPNetwork expected = IPNetwork.Parse("200.16.0.0/22");

            IPNetwork wideSubnet = IPNetwork.WideSubnet(start, end);
            Assert.AreEqual(expected, wideSubnet, "wideSubnet");

Regards
