### ISSUE TITLE
The Parse method parses an invalid IPv4 addresses.

### ISSUE THREAD

**Issue by xirtardauq** [lduchosal/ipnetwork#152]
I found a case that the `IPNetwork.Parse` method accepts an invalid IPv4 addresses.

## Code
```cs
var ip1 = IPNetwork.Parse("122.13.19901");
var ip2 = IPNetwork.Parse("122.13.19901", 32);
```

## Expect
The `Parse` method should throw exceptions in the above two cases.

## Actual
The `ip1` becomes `122.0.0.0/8`.
The `ip2` becomes `122.13.77.189/32`.

## Version
[IPNetwork2 v2.5.307](https://www.nuget.org/packages/IPNetwork2/2.5.307)

**Comment by lduchosal** [comment]
The IPAdress/IPNetwork parsing is delegated to Microsoft's System.Net.IPAdresse.Parse.

It looks like you got confused on what is a valid IPAdress. You may have a look at this document :
https://www.hacksparrow.com/networking/many-faces-of-ip-address.html

Windows and Unix seems to agress that ping 122.13.19901 is valid
> Pinging 122.13.77.189 with 32 bytes of data:

Best regards

**Comment by xirtardauq** [comment]
Thank you for the information and advice. I learned a lot from it.
It turns out that it was my misunderstanding, so I will close this issue.

Best regards,
