### ISSUE TITLE
Semantics of IPNetwork equality

### ISSUE THREAD

**Issue by dotneutron** [lduchosal/ipnetwork#163]
I was parsing a bunch of values and putting them in a `HashSet` when I noticed `IPNetwork.Parse("0.0.0.0/0")` and `IPNetwork.Parse("::0/0")` are essentially treated as being equal, despite the different address families. Is this the intended behavior? If so, can someone shed some light on this?

I dove in the codebase and found the implementation at https://github.com/lduchosal/ipnetwork/blob/1634effbfb5fe9a4ff31e24b6ae69064753352ff/src/System.Net.IPNetwork/IPNetwork.cs#L1916
and this is only taking into account `_network` and `_cidr`.

**Comment by lduchosal** [comment]
Looks like you found a bug.. I'll dig into it.

**Comment by lduchosal** [comment]
fixed in nuget 2.5.337+
