### ISSUE TITLE
Why ::ffff:127.1.0.0/112 FirstUsable is ::ffff:127.1.0.0 rather than ::ffff:127.1.0.1?

### ISSUE THREAD

**Issue by GF-Huang** [lduchosal/ipnetwork#170]
![image](https://user-images.githubusercontent.com/4510984/130737599-c395b1e6-e08f-4098-a7ae-ca800468c543.png)

**Comment by lduchosal** [comment]
There is no such thing as a "Network" neither "Broadcast" address in IPv6. Thus all IPv6 addresses are usable within a range
