### ISSUE TITLE
Supernet example not working in library execution

### ISSUE THREAD

**Issue by uclnj** [lduchosal/ipnetwork#20]

**Comment by lduchosal** [comment]
Not sure about the issue, I'll try to figure out what you mean.

**Comment by lduchosal** [comment]
Unit test suite covers the supernet example :

IPNetworkUnitTest.cs : TestSupernet1 line 2128

            IPNetwork network1 = IPNetwork.Parse("192.168.0.1/24");
            IPNetwork network2 = IPNetwork.Parse("192.168.1.1/24");
            IPNetwork expected = IPNetwork.Parse("192.168.0.0/23");
            IPNetwork supernet = network1.Supernet(network2);

            Assert.AreEqual(expected, supernet, "supernet");

Would you please reopen this issue and provide further details if your use case is still not working.
