### ISSUE TITLE
AssemblyFileVersion is incorrect

### ISSUE THREAD

**Issue by vollt** [lduchosal/ipnetwork#21]
In src/System.Net.IPNetwork/Properties/AssemblyInfo.cs, the version numbers are inconsistent-

```
[assembly: AssemblyVersion("2.1.1.0")]
[assembly: AssemblyFileVersion("2.1.0.0")] // should be 2.1.1.0, as above
```

The result is that the resulting System.Net.IPNetwork.dll lists 2.1.0.0 as the file/product version number.

This can cause issues with builds referencing this package, when the version number of the package does not align with the version number of the DLL.

**Comment by lduchosal** [comment]
Thanks for reporting this, I'll investigate further.
