### ISSUE TITLE
IPNetwork.TryParse on IP return a Network with CIDR not 32

### ISSUE THREAD

**Issue by fravelgue** [lduchosal/ipnetwork#22]
Hello, Doing IPNetwork.TryParse("172.0.0.1", out IPNetwork net), you get a network with CIDR 16. I'm not sure about that but I thought you should get an unique IP or maybe an exception.
Could you explain the reason about TryGuessCidr method?

Thanks,

**Comment by lduchosal** [comment]
IPNetwork.TryParse("172.0.0.1", out IPNetwork net) returns a network with CIDR 8.
This is on purpose as per RFC.

**Comment by fravelgue** [comment]
Thanks for you clarification, my fault for using IPNetwork parsing when I should use ipAddress parsing. So TryGuessCidr functionality comes from RFCs, isn't?
