### ISSUE TITLE
.NET Core2 Support

### ISSUE THREAD

**Issue by dougngo** [lduchosal/ipnetwork#24]
Just installed the package, but doesn't seem to work for Core 2. I'm getting the type or namespace could not be found error.

**Comment by lduchosal** [comment]
The easiest way to use the library is to add the nuget package to your project.
1. Create a new .netcore library or .netcore console app
2. add nuget package ipnetwork2
3. use System.Net
4. have fun...

best regards
Luc

**Comment by lduchosal** [comment]
1. dotnet new console
2. dotnet add pacakge IPNetwork2
3. dotnet restore
4. edit program.cs

```
using System;
using System.Net;

namespace dotnet
{
    class Program
    {
        static void Main(string[] args)
        {
                   var ipn = IPNetwork.Parse("10.0.0.1");
                   Console.WriteLine(ipn.Print());
        }
    }
}
```
5. dotnet run
> IPNetwork   : 10.0.0.0/8
> Network     : 10.0.0.0
> Netmask     : 255.0.0.0
> Cidr        : 8
> Broadcast   : 10.255.255.255
> FirstUsable : 10.0.0.1
> LastUsable  : 10.255.255.254
> Usable      : 16777214
>
