### ISSUE TITLE
Compilation of exe

### ISSUE THREAD

**Issue by samysilva** [lduchosal/ipnetwork#25]
Hello good afternoon.

I downloaded the code, and am trying to compile the application.

The application is compiled successfully, however, I am not finding the compiled program (exe).

I also ran tests with nant, and with Visual Studio.

Apparently the package is correct, however, it is not generating the exe.

     [exec]
     [exec] Build succeeded.
     [exec]     0 Warning(s)
     [exec]     0 Error(s)
     [exec]
     [exec] Time Elapsed 00:00:04.13

Could you check, please?

\src\System.Net.IPNetwork.ConsoleApplication.NetCore\bin\Debug\netcoreapp2.0
\src\System.Net.IPNetwork.ConsoleApplication.NetCore\bin\Release\netcoreapp2.0

**Comment by lduchosal** [comment]
Can you please check that exe compilation now work for latest version ?
Reopen the issue if this is not fixed.
Best regards
