### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by DanAvni** [lduchosal/ipnetwork#251]
Is there a change log file for this project so I can see a list of changes in each version?

**Comment by lduchosal** [comment]
https://github.com/lduchosal/ipnetwork/pulls?q=is%3Apr

**Comment by DanAvni** [comment]
Thanks for the PR list link but at least for me it's not an actual change list. You could merge a PR and then merge later another PR that removes some functionality and it is all hidden behind a sometimes vague title. I think a change log list like this is better
https://github.com/FluentValidation/FluentValidation/blob/main/Changelog.txt

**Comment by lduchosal** [comment]
Thanks @DanAvni 

An similar issue has already been open : https://github.com/lduchosal/ipnetwork/issues/157
Out of 185 merged PR (nuget version), 136 are from dependabot, dependency upgrade.
I can add a manual Changelog.txt with added functionnalities but these are really rare.

**Comment by DanAvni** [comment]
Maybe they are rare but on Nuget package manager I see from time to time updates which also include verion number updates and since I have no idea what has changed in the Nuget package I think a file llike that would be useful

**Comment by lduchosal** [comment]
I do agree on your point.
