### ISSUE TITLE
Feature request: ListUsableIPAddress()

### ISSUE THREAD

**Issue by sandersaares** [lduchosal/ipnetwork#27]
There seems to be a useful `IPNetwork.ListIPAddress()` method that allows one to iterate IP addresses in the network. However, this appears to include all IP addresses, even non-usable. I would like to have an equivalent method that allows me to iterate usable IP addresses, as well.

**Comment by lduchosal** [comment]
Dear sandersaares,

Thanks for your proposal, this may be included in futur release, no promise thought.

Best regards

**Comment by Deantwo** [comment]
Or add an overload to `IPNetwork.ListIPAddress()` with an `emun` for options to exclude network and broadcast addresses.

**Comment by chris03** [comment]
Seems fixed in commit 897ed2304bfd7f090c074865d9d9f988753d13ea

**Comment by lduchosal** [comment]
Fixed
