### ISSUE TITLE
[.NET 8.0] Conflict

### ISSUE THREAD

**Issue by cocoon** [lduchosal/ipnetwork#280]
Hi there,

I just discovered a conflict with the current .NET 8.0 preview 6.

Recently IPNetwork was added to System.Net here:
https://github.com/dotnet/runtime/pull/82779

**Error**

```
Program.cs(3,10): error CS0433: The type 'IPNetwork' exists in both 'System.Net.IPNetwork, Version=2.6.598.0, Culture=neutral, PublicKeyToken=717343cc2c25edcf' and 'System.Net.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [...\test.csproj]

The build failed. Fix the build errors and run again.
```

```
Program.cs(3,10): error CS0433: Der Typ "IPNetwork" ist in "System.Net.IPNetwork, Version=2.6.598.0, Culture=neutral, PublicKeyToken=717343cc2c25edcf" und "System.Net.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" vorhanden. [...\test.csproj]
```

**Steps to reproduce**

- Install .NET 8.0 Prev 6 SDK (x64): [[Download](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.100-preview.6-windows-x64-installer)]
- Start a terminal:
```
mkdir test
cd test
dotnet new console
dotnet add package IPNetwork2
echo var ip = System.Net.IPNetwork.Parse(""); >> Program.cs
rem VERIFY that TargetFramework is net8.0
more test.csproj
dotnet run

```

**Story**

Because of another existing problem (that has nothing to do with IPNetwork), to be able to start processes without windows, I needed to switch to .NET 8 and triggered the conflict.

My current workaround is to rename this IPNetwork class to IPNetwork2.

just for completeness, the other unrelated problem: 

https://github.com/dotnet/runtime/issues/68259

UseShellExecute = false 
+ StartInfo.CreateNoWindow = false
+ StartInfo.WindowStyle = ProcessWindowStyle.Hidden 
+ redirect output

the fix: 
https://github.com/microsoft/playwright-dotnet/pull/2623

**Comment by jeffpatton1971** [comment]
I noticed this as well, it's not a deal breaker for me since I'm not doing anything in .net8 (still preview yes?) but it did look like perhaps several of the namespaces/types are there.

**Comment by Ponderfly** [comment]
<PackageReference Include="IPNetwork2" Version="2.6.609" >
			<Aliases>IPNetwork2</Aliases>
		</PackageReference>

extern alias IPNetwork2;

IPNetwork2.System.Net.IPNetwork

**Comment by loop-evgeny** [comment]
Just ran into this as well. Why is this library, which is not part of the BCL, adding types to the `System` namespace? That's just asking for issues like this.

**Comment by MaxwellDAssistek** [comment]
This needs to be fixed now that .net 8 is GA.

**Comment by Goltom** [comment]
I have the solution in a new branch (locally), I tried to push it but got an access denied:
`Pushing add-dotnet-8-support
Remote: Permission to lduchosal/ipnetwork.git denied to Goltom.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/lduchosal/ipnetwork.git/': The requested URL returned error: 403`

@lduchosal can you allow me (and others) to push new branches?

**Comment by Goltom** [comment]
The fix is on the way! https://github.com/lduchosal/ipnetwork/pull/298

**Comment by lduchosal** [comment]
PR was approved and nuget published
