### ISSUE TITLE
IPNetwork.TryParse throws an exception when provided with "*" 

### ISSUE THREAD

**Issue by louisledev** [lduchosal/ipnetwork#296]
By convention, TryXXX method don't throw but rather returns `false` when failing.
However, when  calling
```
IPNetwork.TryParse("*", out var network);   
```
we get the following exception:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.IPNetwork.InternalParse(Boolean tryParse, String network, ICidrGuess cidrGuess, Boolean sanitanize, IPNetwork& ipnetwork)
   at System.Net.IPNetwork.TryParse(String network, IPNetwork& ipnetwork)
```

tested with version 2.6.618

**Comment by lduchosal** [comment]
PR Welcome

**Comment by lduchosal** [comment]
Cannot reproduce, TestUnit added Test_IPNetwork_TryParse_Issue294 succeed, closing this issue

**Comment by lduchosal** [comment]
Cannot reproduce, TestUnit added Test_IPNetwork_TryParse_Issue294 succeed, closing this issue
