### ISSUE TITLE
Feature request: serialization of the object

### ISSUE THREAD

**Issue by Hyruma** [lduchosal/ipnetwork#30]
Hi,

I'm trying to serialize an object with an ipnetwork inside.
For this purpose i'm using NewtonSoft Json, XML serialization and [zeroformatter](https://github.com/neuecc/ZeroFormatter).
Is it possible to allow serialization with these libraries?

Thanks in advance.

**Comment by Hyruma** [comment]
Thank for your reply. Yes, it can be a solution, but the method ToString() of the class IPNetwork is very slow in terms of computational time.

**Comment by lduchosal** [comment]
Standard .NET serialization has been added (JSON, XML and BinaryFormatter) in version 2.3.0
