### ISSUE TITLE
Assembly should not use BCL namespaces

### ISSUE THREAD

**Issue by alexangas** [lduchosal/ipnetwork#306]
As mentioned in #280 the assembly should not use an overlapping namespace with the BCL as this is bad practice. (It's a bit of a shame this wasn't addressed as part of that rename.)

Is there an alternative namespace that can be used with use of the BCL one deprecated? I'm happy to help with this as I know it may be painful.

**Comment by lduchosal** [comment]
PR Welcome

**Comment by alexangas** [comment]
Thanks @lduchosal - although as the owner of this project and this not insignificant change you should be making the ultimate call here! :smile: I read https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces and tried to come up with some ideas. What do you think about one of these:

* IPUtils.IPNetwork2
* IPUtilities.IPNetwork2
* IPNetworkUtilities.IPNetwork2

I found existing projects on NuGet (besides this one) of IPNetwork and IPNetworkHelper. So perhaps incorporating another word such as Utils or Utilities in the namespace is wise.

**Comment by lduchosal** [comment]
I propose we keep it under System.Net
We already got hit by .NET8. we should be safe for now on.
