### ISSUE TITLE
Supernet - Bug or default behavior?

### ISSUE THREAD

**Issue by BornToBeRoot** [lduchosal/ipnetwork#33]
When i try...

Subnet1 = 192.168.0.0/24
Subnet2 = 192.168.2.0/24

```
var subnet1 = IPNetwork.Parse(Subnet1);
var subnet2 = IPNetwork.Parse(Subnet2);

var subnet = subnet1.Supernet(subnet2);
```

an exception is thrown...

![image](https://user-images.githubusercontent.com/16019165/47389060-0cde1980-d714-11e8-8eea-283f7db2501c.png)

The output i expect should be 192.168.0.0/22 or am i wrong?

Using this as input works fine:

Subnet1 = 192.168.0.0/24
Subnet2 = 192.168.1.0/24

Result --> 192.168.0.0/23

**Comment by lduchosal** [comment]
Supernet _requires_ consecutive subnet without missing IP

        /// <summary>
        /// Supernet two consecutive cidr equal subnet into a single one
        /// 192.168.0.0/24 + 192.168.1.0/24 = 192.168.0.0/23 
        /// 10.1.0.0/16 + 10.0.0.0/16 = 10.0.0.0/15
        /// 192.168.0.0/24 + 192.168.0.0/25 = 192.168.0.0/24 
        /// </summary>
        /// <param name="network2"></param>
        /// <returns></returns>
        public IPNetwork Supernet(IPNetwork network2) {

You are looking for the WideSubnet functionnality.


         IPNetwork network1 = IPNetwork.Parse("192.168.0.0/24");
         IPNetwork network2 = IPNetwork.Parse("192.168.2.0/24");
         IPNetwork expected = IPNetwork.Parse("192.168.0.0/22");
         IPNetwork widenetwork = IPNetwork.WideSubnet(new[] { network1, network2 });
   
         Assert.AreEqual(expected, widenetwork, "widesubnet");

**Comment by BornToBeRoot** [comment]
@lduchosal the wide subnet feature works perfect for IPv4. 

With IPv6 i get the following error:
![image](https://user-images.githubusercontent.com/16019165/48973521-63a37f80-f041-11e8-8c71-3713da752a85.png)
