### ISSUE TITLE
How to get next address

### ISSUE THREAD

**Issue by nielsvdc** [lduchosal/ipnetwork#5]
I'm trying to figure out how to get the next IP address in an easy way. So for example, I have IP address 10.230.234.56. How do I with easy en fast coding get IP address 10.230.234.56. Here an example of a slow search.

    var myip = "10.230.234.56";
    var net = IPNetwork.Parse(myip, 10);
    var list = IPNetwork.ListIPAddress(net);
    IPAddress next;
    foreach (var ip in list)
    {
        if (ip.ToString().Equals(myip))
        {
            list.MoveNext();
            next = list.Current;
        }
    }

**Comment by lduchosal** [comment]
Have you tried this one  :
var intip = IPAddress.NetworkToHostOrder(
             (int) IPAddress.Parse(addr).Address);
var next = intip++;
