### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by sidshetye** [lduchosal/ipnetwork#6]
Which is the official NuGet package? If you look at https://www.nuget.org/packages?q=IPNetwork you'll see two packages,

* https://www.nuget.org/packages/IPNetwork/
* https://www.nuget.org/packages/System.Net.IPNetwork

And both seem to be by you. Can you clarify the relationship between those two packages and this GitHub project?

**Comment by lduchosal** [comment]
The official NuGet package is 
https://www.nuget.org/packages/System.Net.IPNetwork

**Comment by sidshetye** [comment]
There is a warning on that page, as of 1/4/2016

> The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore.

**Comment by lduchosal** [comment]
Thanks for pointing this out.
