### ISSUE TITLE
Adding ipnetwork2 as a dependency breaks nuget package generation

### ISSUE THREAD

**Issue by FrankyBoy** [lduchosal/ipnetwork#60]
Hi,

Basically, adding ipnetwork2 as a dependency breaks nuget package generation with the following error: `Part URI is not valid per rules defined in the Open Packaging Conventions specification.`

Simple project to reproduce: [ClassLibrary1.zip](https://github.com/lduchosal/ipnetwork/files/3166750/ClassLibrary1.zip). Just run `nuget pack .\ClassLibrary1\ClassLibrary1.csproj` in the solution folder (after build ofc) to reproduce.

Maybe this is specific to .net framework 4.6.2 but I kinda doubt it (need to try though). I will do a quick test on 4.7 and core as well now and see how that behaves. 

Cheers!

**Comment by FrankyBoy** [comment]
More tests ... 

* on .net standard, "dotnet pack" works as intended
* .net Framework 4.6.2 works when using package references instead of packages.json

So this seems to be an issue when using packages.json only.

**Comment by FrankyBoy** [comment]
PS: on ".net Framework 4.6.2 works when using package references instead of packages.json" ... that's actually because nuget.exe ignores references that are specified as package references.

**Comment by lduchosal** [comment]
Did you run "nuget restore" before "nuget pack" ?
It looks like everything is OK with this package ...

> 
> C:\Users\x\Downloads\ClassLibrary1>"C:\Program Files (x86)\bin\nuget.exe" restore
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Restoring NuGet package IPNetwork2.2.4.0.99.
> Adding package 'IPNetwork2.2.4.0.99' to folder 'C:\Users\x\Downloads\ClassLibrary1\packages'
> Added package 'IPNetwork2.2.4.0.99' to folder 'C:\Users\x\Downloads\ClassLibrary1\packages'
> 
> NuGet Config files used:
>     C:\Users\x\AppData\Roaming\NuGet\NuGet.Config
>     C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
> 
> Feeds used:
>     C:\Users\x\.nuget\packages\
>     https://api.nuget.org/v3/index.json
>     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
> 
> Installed:
>     1 package(s) to packages.config projects
> 
> C:\Users\x\Downloads\ClassLibrary1>"C:\Program Files (x86)\bin\nuget.exe" pack .\ClassLibrary1\ClassLibrary1.csproj
> Attempting to build package from 'ClassLibrary1.csproj'.
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Packing files from 'C:\Users\x\Downloads\ClassLibrary1\ClassLibrary1\bin\Debug'.
> Found packages.config. Using packages listed as dependencies
> WARNING: Description was not specified. Using 'Description'.
> WARNING: Author was not specified. Using 'x'.
> Successfully created package 'C:\Users\x\Downloads\ClassLibrary1\ClassLibrary1.1.0.0.nupkg'.
>
