### ISSUE TITLE
Some of the IPv6 address cannot be parsed

### ISSUE THREAD

**Issue by psimax** [lduchosal/ipnetwork#7]
Some of the valid IPv6 address and ranges cannon be parsed by the library.
Example of valid address:
2FFF:FFFF:123::/60  - INVALID
2FFF:FFFE:123::/60  - INVALID
2FFF:FFFC:123::/60  - INVALID
2FFF:FFFA:123::/60  - INVALID
2FFF:FFF9:123::/60  - VALID
FFFF:FFF1:123::/60  - INVALID

**Comment by psimax** [comment]
As it's appears IpNetwork API is inconsistent with the IPAddress API.
IPAddress can accept upper case hex chars but IPNetwork cannot.

Issue can be resolved by extension of validating regex expression to accept UpperCase letters

**Comment by lduchosal** [comment]
Thanks for pointing this out, I will deepen further into the issue.

**Comment by lduchosal** [comment]
Fixed. Thanks for you insight.
