### ISSUE TITLE
Feature request: merge Ip ranges

### ISSUE THREAD

**Issue by imaculate** [lduchosal/ipnetwork#87]
Would be nice if this package supported merging (or TryMerge) networks.

**Comment by lduchosal** [comment]
Dear Imaculate,

Thanks for your feedback.

I think the merging you are looking for already exists in the current version.

It is called Supernetting (like the opposite of Subnetting). 
The methods are called TrySupernet(). ..

Would you have a look and tell me if it fits your needs.

Best regards

**Comment by lduchosal** [comment]
Example 9
```
IPNetwork ipnetwork1 = IPNetwork.Parse("192.168.0.0/24");
IPNetwork ipnetwork2 = IPNetwork.Parse("192.168.1.0/24");
IPNetwork[] ipnetwork3 = IPNetwork.Supernet(new[]{ipnetwork1, ipnetwork2});

Console.WriteLine("{0} + {1} = {2}", ipnetwork1, ipnetwork2, ipnetwork3[0]);
Output

192.168.0.0/24 + 192.168.1.0/24 = 192.168.0.0/23
```
