### ISSUE TITLE
IPv6 addresses are not parsed correctly

### ISSUE THREAD

**Issue by maggu** [lduchosal/ipnetwork#9]
"::1" is parsed as "::/64, and then match any IPv4 address.

For example, this returns True: IPNetwork.Contains(IPNetwork.Parse("::1"), IPAddress.Parse("8.8.8.8"))

I think there are two issues here:
1. IPNetwork objects should contain an AddressFamily property and IPNetwork.Contains() always return False if the address families are not the same.
2. If netmask isn't specified IPNetwork.Parse() should set the maximum netmask (/32 for IPv4 and /128 for IPv6).

**Comment by lduchosal** [comment]
Thanks for pointing this out, I will deepen further into the issue.

**Comment by lduchosal** [comment]
1. Contains now check AddressFamily property
2. Default netmask are parsed as per RFC.

Thanks for your insights.
