### ISSUE TITLE
Update Web Site Examples

### ISSUE THREAD

**Issue by BigPacket** [lduchosal/ipnetwork#90]
Greetings,

I just wanted to know if there was any plans to update the Web Site examples? For instance example 8 creates the following error: "System.Net.IPNetworkCollection' to 'System.Net.IPNetwork" with version version 2.4.0.

**Comment by lduchosal** [comment]
Thank you for your report. I'll have a look

**Comment by lduchosal** [comment]
This is fixed now, thanks for your help !
