### ISSUE TITLE
Example 9 is broken

### ISSUE THREAD

**Issue by BigPacket** [lduchosal/ipnetwork#97]
Greetings,

Example 9 seems to be broken if you use 192.168.0.0/24 + 192.168.1.0/24 = 192.168.0.0/23, then it's correct. 

But if you use another IP, say "192.168.0.0/24 + 192.168.10.0/24 = 192.168.0.0/24". This should have been CIDR /20, not 24 for the supernet.

**Comment by lduchosal** [comment]
Dear BigPacket,

Thanks for your question. There are 2 methodes that behave almost identically :

   IPNetwork.TrySupernet
   IPNetwork.TryWideSubnet

TrySupernet will merge only consecutive subnets (192.168.0.0/24 + 192.168.1.0/24 = 192.168.0.0/23)
TryWideSubnet will find the smallest subnet that can contains the subnet in argument (192.168.0.0/24 + 192.168.10.0/24 = 192.168.0.0/20)

https://github.com/lduchosal/ipnetwork/blob/master/src/System.Net.IPNetwork.TestProject.Source/IPNetworkUnitTest.cs

`

        [TestMethod]
        public void When_TrySupernet_192_168_0_0_cidr24_add_192_168_10_0_cidr24_Then_Should_Invalid()
        {

            IPNetwork network = IPNetwork.Parse("192.168.0.0/24");
            IPNetwork network2 = IPNetwork.Parse("192.168.10.0/24");

            bool supernetted = network.TrySupernet(network2, out var ipnetwork);
            Assert.AreEqual(false, supernetted);


        }

        [TestMethod]
        public void When_TryWideSubnet_192_168_0_0_cidr24_add_192_168_10_0_cidr24_Then_Should_Invalid()
        {

            IPNetwork network = IPNetwork.Parse("192.168.0.0/24");
            IPNetwork network2 = IPNetwork.Parse("192.168.10.0/24");

            bool wideSubnetted = IPNetwork.TryWideSubnet(new[] { network, network2 }, out IPNetwork ipnetwork);
            Assert.AreEqual(true, wideSubnetted);
            Assert.AreEqual("192.168.0.0/20", ipnetwork.ToString());

            Console.WriteLine("Network : {0}", ipnetwork.Network);
            Console.WriteLine("Netmask : {0}", ipnetwork.Netmask);
            Console.WriteLine("Broadcast : {0}", ipnetwork.Broadcast);
            Console.WriteLine("FirstUsable : {0}", ipnetwork.FirstUsable);
            Console.WriteLine("LastUsable : {0}", ipnetwork.LastUsable);
            Console.WriteLine("Usable : {0}", ipnetwork.Usable);
            Console.WriteLine("Cidr : {0}", ipnetwork.Cidr);

        }

`

Hope this helps.
Best regards
Luc
